import { Routes } from '@angular/router';
import { accessGuard, authGuard, guestGuard } from './core/guards';

export const routes: Routes = [
  { path: 'login', canActivate: [guestGuard], loadComponent: () => import('./auth/login').then(m => m.LoginComponent) },
  {
    path: '',
    canActivate: [authGuard],
    loadComponent: () => import('./layout/shell').then(m => m.ShellComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', canActivate: [accessGuard], data: { permission: 'Dashboard.View' }, loadComponent: () => import('./dashboard/dashboard').then(m => m.DashboardComponent) },
      { path: 'pos', canActivate: [accessGuard], data: { permission: 'Order.Create', feature: 'restaurantManagement' }, loadComponent: () => import('./pos/pos').then(m => m.PosComponent) },
      { path: 'orders', canActivate: [accessGuard], data: { permission: 'Order.View' }, loadComponent: () => import('./pos/orders').then(m => m.OrdersComponent) },
      { path: 'kitchen', canActivate: [accessGuard], data: { permission: 'Kitchen.View' }, loadComponent: () => import('./kitchen/kitchen').then(m => m.KitchenComponent) },
      { path: 'bar/pos', canActivate: [accessGuard], data: { permission: 'Order.Create', feature: 'barManagement', area: 'Bar' }, loadComponent: () => import('./pos/pos').then(m => m.PosComponent) },
      { path: 'bar/stock', canActivate: [accessGuard], data: { permission: 'Bar.View', feature: 'barManagement' }, loadComponent: () => import('./bar/bar-stock').then(m => m.BarStockComponent) },
      { path: 'bar/brands', canActivate: [accessGuard], data: { permission: 'Bar.View', feature: 'barManagement' }, loadComponent: () => import('./bar/bar-catalog').then(m => m.BarCatalogComponent) },
      { path: 'bar/drinks', canActivate: [accessGuard], data: { permission: 'Bar.View', feature: 'barManagement' }, loadComponent: () => import('./bar/bar-drinks').then(m => m.BarDrinksComponent) },
      { path: 'inventory/stock', canActivate: [accessGuard], data: { permission: 'Inventory.View', feature: 'inventory' }, loadComponent: () => import('./inventory/stock').then(m => m.InventoryStockComponent) },
      { path: 'inventory/adjustments', canActivate: [accessGuard], data: { permission: 'Inventory.View', feature: 'inventory', initialTab: 'movements' }, loadComponent: () => import('./inventory/stock').then(m => m.InventoryStockComponent) },
      { path: 'inventory/purchases', canActivate: [accessGuard], data: { permission: 'Purchase.View', feature: 'inventory' }, loadComponent: () => import('./purchase/purchases').then(m => m.PurchasesComponent) },
      { path: 'inventory/suppliers', canActivate: [accessGuard], data: { permission: 'Purchase.View', feature: 'inventory' }, loadComponent: () => import('./inventory/setup').then(m => m.SuppliersComponent) },
      { path: 'inventory/items', canActivate: [accessGuard], data: { permission: 'Inventory.View', feature: 'inventory' }, loadComponent: () => import('./inventory/setup').then(m => m.InventorySetupComponent) },
      { path: 'inventory/recipes', canActivate: [accessGuard], data: { permission: 'Inventory.View', feature: 'inventory' }, loadComponent: () => import('./inventory/recipes').then(m => m.RecipesComponent) },
      { path: 'reservations', canActivate: [accessGuard], data: { permission: 'Reservation.View', feature: 'reservation' }, loadComponent: () => import('./reservation/reservations').then(m => m.ReservationsComponent) },
      { path: 'loyalty', canActivate: [accessGuard], data: { permission: 'Loyalty.View', feature: 'loyalty' }, loadComponent: () => import('./crm/loyalty').then(m => m.LoyaltyComponent) },
      { path: 'offers', canActivate: [accessGuard], data: { permission: 'Loyalty.View', feature: 'loyalty' }, loadComponent: () => import('./crm/offers').then(m => m.OffersComponent) },
      { path: 'tables', canActivate: [accessGuard], data: { permission: 'Table.View', feature: 'restaurantManagement' }, loadComponent: () => import('./restaurant/tables').then(m => m.TablesComponent) },
      { path: 'menu', canActivate: [accessGuard], data: { permission: 'Menu.View', feature: 'restaurantManagement' }, loadComponent: () => import('./menu/menu-items').then(m => m.MenuItemsComponent) },
      { path: 'menu/categories', canActivate: [accessGuard], data: { permission: 'Menu.View', feature: 'restaurantManagement' }, loadComponent: () => import('./menu/menu-categories').then(m => m.MenuCategoriesComponent) },
      { path: 'customers', canActivate: [accessGuard], data: { permission: 'Customer.View' }, loadComponent: () => import('./crm/customers').then(m => m.CustomersComponent) },
      { path: 'finance/expenses', canActivate: [accessGuard], data: { permission: 'Expense.View' }, loadComponent: () => import('./finance/expenses').then(m => m.ExpensesComponent) },
      { path: 'finance/expense-categories', canActivate: [accessGuard], data: { permission: 'Expense.View' }, loadComponent: () => import('./finance/expenses').then(m => m.ExpenseCategoriesComponent) },
      { path: 'finance/settings', canActivate: [accessGuard], data: { permission: 'Payment.View' }, loadComponent: () => import('./finance/finance-settings').then(m => m.FinanceSettingsComponent) },
      { path: 'reports', canActivate: [accessGuard], data: { permission: 'Reports.View' }, loadComponent: () => import('./reports/reports').then(m => m.ReportsComponent) },
      { path: 'admin/users', canActivate: [accessGuard], data: { permission: 'User.View' }, loadComponent: () => import('./admin/users').then(m => m.UsersComponent) },
      { path: 'admin/roles', canActivate: [accessGuard], data: { permission: 'Role.View' }, loadComponent: () => import('./admin/roles').then(m => m.RolesComponent) },
      { path: 'admin/settings', canActivate: [accessGuard], data: { permission: 'Tenant.View' }, loadComponent: () => import('./admin/tenant-settings').then(m => m.TenantSettingsComponent) },
      { path: 'staff/employees', canActivate: [accessGuard], data: { permission: 'Staff.View', feature: 'staff' }, loadComponent: () => import('./staff/staff-setup').then(m => m.EmployeesComponent) },
      { path: 'staff/attendance', canActivate: [accessGuard], data: { permission: 'Staff.View', feature: 'staff' }, loadComponent: () => import('./staff/attendance').then(m => m.AttendanceComponent) },
      { path: 'staff/leave', canActivate: [accessGuard], data: { permission: 'Staff.View', feature: 'staff' }, loadComponent: () => import('./staff/leave').then(m => m.LeaveComponent) },
      { path: 'staff/setup', canActivate: [accessGuard], data: { permission: 'Staff.View', feature: 'staff' }, loadComponent: () => import('./staff/staff-setup').then(m => m.StaffSetupComponent) },
      { path: 'forbidden', loadComponent: () => import('./layout/forbidden').then(m => m.ForbiddenComponent) },
    ],
  },
  { path: '**', redirectTo: '' },
];
